### ISSUE TITLE
Chrome Browser: "Uncaught TypeError: Illegal invocation"

### ISSUE THREAD

**Issue by kenaniah** [qTip2/qTip2#183]
Uncaught TypeError: Illegal invocation

This occurs in Google Chrome 12.0.742.100 due to line 49 of jquery.qtip.js, which reads:

```
    if(console){
        (console.warn || console.log)(Array.prototype.slice.call(arguments));
    }
```

Altering the middle line to read `console.warn(Array.prototype.slice.call(arguments));` works in chrome as expected.

**Comment by tjvg91** [comment]
How did ya fix this
