### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pageY' of null

### ISSUE THREAD

**Issue by szivak009** [qTip2/qTip2#187]
Hi!

First of all, thanks for qTip. It's a great tooltip. However, I found an error in Google Chrome. (Error doesn't show up in FireFox 3.6.17)

Description:
I was just testing qtip. I made a link and loaded content into the tooltip with ajax. When I move my mouse over the link, the tooltip should appear and should follow my mouse. What happens is it appears, and stays in one place and if I take away my cursor and move it back, it disappears and never shows again. Although, the content gets loaded at first enter.

I've checked the Javascript console and found this:

``` html
Uncaught TypeError: Cannot read property 'pageY' of null
a.extend.repositionjquery.qtip.min.js:13
a.extend.setjquery.qtip.min.js:13
$.qtip.content.ajax.success/tooltip_comparison/:108
f.extend._Deferred.e.resolveWithjquery-1.6.2.min.js:16
wjquery-1.6.2.min.js:18
f.support.ajax.f.ajaxTransport.send.d
```

Here's my code:

``` javascript
$('#ajax').qtip({
                    content: {
                        text: 'Loading...',
                        ajax: {
                            url: 'ajax.php',
                            type: 'POST',
                            data: ad,
                            dataType: 'json',
                            success: function(data, status) {
                                this.set('content.text',data.text);
                            }
                        }
                    },
                    position: {
                        target: 'mouse',
                        adjust: {
                            mouse: true
                        }
                    }
});
```

jQuery version: 1.6.2
Browser: Google Chrome 10.0.648.204

Thank you.

**Comment by shrewdlogarithm** [comment]
I realise this is age-old and qtip2 hasn't been updated in a long while, but I ran into this error earlier and I think I know the cause (at least MY cause)

In position.js there's the following code

`````
		else if(!event || (event && (event.type === 'resize' || event.type === 'scroll'))) {
			event = cache.event;
		}

		// Otherwise, use the cached mouse coordinates if available
		else if(mouse && mouse.pageX) {
			event = mouse;
		}
`````

The first 'else' DOESN'T check that cache.event contains anything - so for events which fire when cache.event is empty, event will be assigned to null (when it should be assigned to mouse - in the following 'else'??

Certainly adding "cache.event &&" to the first else solved my issue...
