### ISSUE TITLE
Destroy/hide event breaks if event is initialized from inside the qtip.

### ISSUE THREAD

**Issue by coppermind** [qTip2/qTip2#476]
qTip2 normal behavior is usually that when the selector is removed from the page the qtip popup hides itself. We are trying to use it wherein the element that initializes the reset/hide action for the selector is inside the qtip itself. This breaks the close method and the qtip fails to hide itself.

We are currently employing a workaround by inserting a 'hide' call when the selector is refreshed. eg. $(selector, context).qtip('hide');

**Comment by smorsi** [comment]
Guys, this bug still occurs in qtip2 v2.2.0!!
