### ISSUE TITLE
qTip2 TypeScript Definition File

### ISSUE THREAD

**Issue by tstar** [qTip2/qTip2#567]
Is it possible to create TypeScript Definition File for qTip2 as a part of the project? Thank you.

**Comment by Seltzer** [comment]
I've recently written some type bindings which you can find [here](https://github.com/borisyankov/DefinitelyTyped/tree/master/qtip2).

**Comment by Craga89** [comment]
Awesome (y) I'll update the docs with these for those looking for them

**Comment by tstar** [comment]
Excellent. Many thanks.
