### ISSUE TITLE
AJAX content setting repositions tooltip

### ISSUE THREAD

**Issue by bjohnson045** [qTip2/qTip2#667]
Using your "XMLHTTPRequest (AJAX)" guide example with 2.2 has a problem.  The "Loading.." message shows, but once the content gets set from the AJAX response the tooltip position seems to reset and "slides" back to its original position.

**Comment by mixedconnections** [comment]
I had this same problem, and I couldn't find a fix. I read many posts. Setting position.effect to false didn't help. The best option I found was what kevinranks posted here. The modal still jumps to position sometimes, but it is less frequent than before.
