### ISSUE TITLE
Bower.json

### ISSUE THREAD

**Issue by Melonbwead** [qTip2/qTip2#687]
Shouldn't the main option be pointing at qtip's files rather than imageloaded inside the bower.json.
https://github.com/qTip2/qTip2/blob/master/bower.json#L5

Or is the bower side of things not being maintained at the moment in qTip?

**Comment by jgillich** [comment]
@Craga89 Can you update the docs? http://qtip2.com/guides#gettingstarted.bower

When I do `bower install qTip2`, I get the source code, not the above repo.

**Comment by Craga89** [comment]
Use the lowercase `qtip2` not `qTip2`, as it's been wrongly registered by some else I think. I'll look into this
