### ISSUE TITLE
Add css file to npm distribution

### ISSUE THREAD

**Issue by StreetStrider** [qTip2/qTip2#716]
Hello.
npm package `qtip2` lacks of css table.
```sh
$ npm install qtip2
```
```sh
$ ls ./node_modules/qtip2 
jquery.qtip.min.js
package.json
README.md
```
CSS-file must be added to npm package.

**Comment by janusch** [comment]
Is there at all an official npm dist?

This repo has a package.json but I cannot find qTip2 on npmjs.org

Any plans to make qTip commonJs or UMD compatible?

Cheers

**Comment by Craga89** [comment]
See #755
