### ISSUE TITLE
TypeError: this.timers is null

### ISSUE THREAD

**Issue by alokpant** [qTip2/qTip2#718]
I am implementing multiple qtips on the same page.

``` javascript
  $('[data-info!=""]').on('mouseover', function () {
    if($(this).attr('data-info')) {
      $(this).qtip({
        content: {
            attr: 'data-info'
        },
        position: {
            my: 'top center',
            at: 'bottom center'
        },
        show: {
          ready: true
        }
      });
    }
  });

```

But when I hover on each element, I get this error:

```
TypeError: this.timers is null
clearTimeout(this.timers.show);

```

This does not effect the output, all tooltips are displayed properly. But having the message is still not desired.

Thank you.

![error](https://cloud.githubusercontent.com/assets/6135761/5506774/9e35f9f4-879d-11e4-98e5-a79ebf0630e4.jpg)

**Comment by Craga89** [comment]
Can you setup a reduced test case please? http://jsfiddle.net/fDavN/

**Comment by alokpant** [comment]
https://jsfiddle.net/amrebel/oqrtk1cm/

If you hover on to the elements more than once, you will get the error message in console.

**Comment by titombo** [comment]
I have the same error

**Comment by alokpant** [comment]
@titombo not yet. still have that problem. It doesn't effect any functionality though. Please share if you find any solution on it.

**Comment by Loadir** [comment]
http://jsfiddle.net/Lfqpwpdr/11/#&togetherjs=mSKiGmDJl7

**Comment by CVA-Andrey** [comment]
Do you have any updates on this issue ?
It still presents in latest version (3.0.3)

**Comment by stavultras** [comment]
Was able to fix it via:
```javascript
$object.on('mouseenter', function()
{
  if ($(this).prop('hint'))
  {
    qtip_options['content'] = $(this).prop('hint');

    $(this).qtip(qtip_options);
  }
}).on('mouseleave', function()
{
  $(this).qtip('destroy');
});
```

**Comment by CVA-Andrey** [comment]
> Was able to fix it via:
> 
> ```js
> $object.on('mouseenter', function()
> {
>   if ($(this).prop('hint'))
>   {
>     qtip_options['content'] = $(this).prop('hint');
> 
>     $(this).qtip(qtip_options);
>   }
> }).on('mouseleave', function()
> {
>   $(this).qtip('destroy');
> });
> ```

I can confirm that it works, thanks.

**Comment by thereafter** [comment]
https://github.com/qTip2/qTip2/pull/851/commits/bd406f5ee2976e01c4587165178165e4fb6c5eba

**Comment by alokpant** [comment]
Thank you for fix. I do not use qTip anymore. Going to close the issue.
