### ISSUE TITLE
Avoid duplicate divs in qtip2 in angularjs code

### ISSUE THREAD

**Issue by ricardmestre** [qTip2/qTip2#725]
Hi everyone,

I am working with qtip2 in angularjs code, but I have a problem with the code:

```
angular.module('something.directives')
    .directive('gfTip', function($parse) {
      return {
        restrict: 'A',
        link: function(scope, element, attrs) {
          var getter = $parse(attrs.gfTip), value = getter(scope);
          var my = attrs.my || 'top center';
          var at = attrs.at || 'bottom center';
          var content;

          if (value) {
            content = { 'text': value, title: 'This is a just a test' };
          }
          else {
            content = attrs.content;
          }

          element.qtip({
            content: content,
            position: {
              my: my,
              at: at,
            },
            style: { classes: 'qtip-dark' }
          });
        }
      };
    });
``` 

The problem is that this is creating a \<div\> for every qtip atribute, and I want only one \<div\> that changes for every qtip atribute. 

![image](https://cloud.githubusercontent.com/assets/8693668/5738592/5f5a2c9a-9bee-11e4-8bc3-e812c93b2f3e.png)

Could anyone help me?
Thank you!

**Comment by Craga89** [comment]
This is the correct behaviour; a tooltip for each element matched by the selector.

If you want a single <div/> for all elements, see here: http://craigsworks.com/projects/forums/showthread.php?tid=4201&highlight=shared
