### ISSUE TITLE
Fix CDN  sourceMappingURL

### ISSUE THREAD

**Issue by numediaweb** [qTip2/qTip2#732]
There's an error in the URL of the map file in the [minified jquery.qtip.min.js](http://cdnjs.cloudflare.com/ajax/libs/qtip2/2.2.1/basic/jquery.qtip.min.js) hosted in both CDNs!

**Comment by kennethmac2000** [comment]
Also seeing this. It's resulting in a slightly annoying error message in browser consoles. A quick fix would be awesome!

**Comment by nateous** [comment]
also, where is https://cdn.jsdelivr.net/qtip2/2.2.1//var/www/qtip2/build/tmp/tmp-6564t0090xs/imagesloaded.pkg.min.map ?

**Comment by jimaek** [comment]
The path is wrong. Looks like a bug of the build system, it injected the local path to the URL

**Comment by nateous** [comment]
true, but I tried removing the extra slash and it still seems to be missing, the zip doesn't include the file so you can't even include it locally

**Comment by jonahgreenthal** [comment]
:thumbsup:

**Comment by Craga89** [comment]
The map files are no hosted in the CDNs, too :).
