### ISSUE TITLE
qtip2.js and webcomponents.js cause HTML select element to malfunction

### ISSUE THREAD

**Issue by trevorhreed** [qTip2/qTip2#737]
See [jsfiddle](http://jsfiddle.net/y61w1Ltm/)

When webcomponents.js and qtip2.js are on the same page, they cause HTML Select elements to malfunction, requiring a user to double-click in order open the select list.

**Comment by Craga89** [comment]
That doesn't seem to be the case in your fiddle any longer. Closing this
