### ISSUE TITLE
Does qTip have an extension API

### ISSUE THREAD

**Issue by Sebazzz** [qTip2/qTip2#741]
I am currently writing a  wrapper for qTip to use it as a lightbox (iframe) equivalent. This works quite well. However, I am having trouble finding a good API design for this wrapper. I think it would be best if it could be plugged into qTip as a plugin, but I'm having trouble finding an extension point on qTip. Does qTip have such extension point?

**Comment by Craga89** [comment]
It has a full fledged API, see the API section: http://qtip2.com/guides

**Comment by Sebazzz** [comment]
Yes I know, but note the word "extension". Perhaps I was not clear, I meant a way to hook up custom logic at certain points so it is possible to create an extension or plugin for qTip.

**Comment by Craga89** [comment]
Well, you can override any of the prototype methods you want by inspecting and altering the `$.qtip.prototype`. Is this what you mean? It really depends on what you're trying to achieve, but most if not all of the API is publicly accessible, even the internals (prefixed with `_`).
