### ISSUE TITLE
How to show real-time continuous in qtip2?

### ISSUE THREAD

**Issue by tanobi92** [qTip2/qTip2#745]
I use qtip2 http://qtip2.com/ I want to when I hover a tag show tooltip with content is real time continuous. It like to show a clock with time change continuous. 
Help me, please! Thank you very much!

**Comment by Craga89** [comment]
Take a look at the integration and API docs for a better idea of how to achieve this: http://qtip2.com/guides#integration.within

Here's a rough idea 

```js
$('.selector').qtip({
    content: 'Loading...',
    events: {
        render: function(api) {
            // Grab the content
            var content = api.elements.content;
            
            api.contentTimer = setTimeout(function() { 
            	content.html(new Date());
            },
            1000);
        }
    }
});
```

**Comment by tanobi92** [comment]
Hi @Craga89, Thank you for re-answer.
Utils.toolTip = function(){
		var interval;
		$('td').on("mouseover", function(e) {
			var hist, str,strchild, texts = '';
			if(this.hasAttribute(ATTRIBUTE_HIST)){
				hist = this.getAttribute(ATTRIBUTE_HIST);
				//console.log(hist)
				if (hist.indexOf('|') == -1) {
				    strchild = hist.split('=');
				    //texts = TEMPLATE_COOKIE_HIST.replace('Date=Value', '...' + hist);
				    texts = TEMPLATE_TABLE_TOOLTIP.replace('<tr></tr>', '<tr><td>' + strchild[0] + '</td><td>' + strchild[1] + '</td><tr>');
				}
				else{
				    str = hist.split('|');
				    var trs = '';
				    $.each(str, function (index, data) {
				        strchild = data.split('=');
					    //texts += TEMPLATE_COOKIE_HIST.replace('Date=Value', '...' + data);
				        trs += '<tr><td>' + strchild[0] + '</td><td>' + strchild[1] + '</td></tr>';
					})
				    texts = TEMPLATE_TABLE_TOOLTIP.replace('<tr></tr>', trs);
				}
				if(hist != ''){
					$(this).qtip({
						overwrite: true,
						style: { classes: 'qtip-bootstrap' },
						position: {
							my: 'bottom center',
							at: 'top center',
							viewport: $(window)
						},
						show: {
							event: e.type,
							ready: true
						},
						content: 'Loading...',
						events: {
						    render: function (api) {
						        // Grab the content
						        var content = api.elements.content;

						        api.contentTimer = setTimeout(function () {
						            content.html(texts);
						        },
                                1000);
						    }
						},
						hide: {
							delay: 200,
							fixed: true, // <--- add this
							effect: function() { $(this).fadeOut(250); }
						}
					}, e);
				}
			}
			
		});
		$('td').on("mouseout", function(e) {
			$(this).qtip('destroy',true);
		})
	}
F12 debug: console: Uncaught TypeError: Cannot read property 'content' of undefined.

**Comment by Craga89** [comment]
Sorry there was a slight mistake in my code, `api` is the second param, `event` is the first

```js
render: function(event, api) {
```

**Comment by tanobi92** [comment]
Yep, it true, @Craga89 ! I also can use other way:
                                         var qtip = $($this).qtip({
                                          // my code
                                               content: {
						    text:new Date
							//title: 'Noi dung'
						}
                                        // my code
and outside qtip:           window.setInterval(function () {
					    qtip.qtip('option', 'content.text', new Date)
					}, 1000);
Thank you very much! :)
