### ISSUE TITLE
qTip applied on virtual Dom

### ISSUE THREAD

**Issue by abauzac** [qTip2/qTip2#746]
Hello, 

First, thanks a lot for this lib ! Helped a *lot* so I hope you'll keep it up !

This post is not really an issue, more like a enhancement. It would be nice to have qTip working on virtual dom (not sure it's correct, I mean a dom created using JS and not yet inserted in the HTML).

I've done a quick codepen to reproduce here http://codepen.io/bqlou/pen/MwKjRO

(Maybe it's already possible and I'm mistaking somewhere too..)

Have a good day!

**Comment by Craga89** [comment]
This is possible, you just need to make sure you *append* the DOM element you create, not set the innerHTML of the target element to it, since it won't be the same node then :) 

See http://codepen.io/anon/pen/LVNjOQ
