### ISSUE TITLE
'oldtitle' does not validate

### ISSUE THREAD

**Issue by webbird** [qTip2/qTip2#751]
I'm sorry if I missed this in the docs. I just used the W3C-Validator to check a page and got lots of errors because of the 'oldtitle' attribute. I am _not_ looking for option 'suppress', instead I'd like to suggest to use 'data-oldtitle' instead of 'oldtitle'. (Or allow to set the attribute name to store the old title.)

**Comment by Craga89** [comment]
The attribute is added dynamically to the page and as such isn't really an issue to be valid. Only HTML there on page load is the stuff you should be concerned about imo.

**Comment by webbird** [comment]
I patched my min.js to use data-oldtitle (there's only one occurance), seems to work perfectly. Maybe you could consider this suggestion for a future release.
