### ISSUE TITLE
Publish as npm module

### ISSUE THREAD

**Issue by Magomogo** [qTip2/qTip2#755]
Could we have an official npm qtip2 module, please? :)

**Comment by Craga89** [comment]
:+1: Will do so as soon as I get chance

**Comment by Atsman** [comment]
When are you going to do that?

**Comment by rockerest** [comment]
+1 would love to see a dist version in NPM. Can't currently use QTip2 (the only useful OSS tooltip library) in my applications.

**Comment by Craga89** [comment]
Looks like it's already published by another user quite a while ago: https://www.npmjs.com/package/qtip2

I've got in contact asking for ownership, so I'll update here once I have a response!

**Comment by Craga89** [comment]
Done as of the `v3.0.0` tag (71eb15cff024ad698704fd67c167b6e8ca3522a8)

**Comment by rockerest** [comment]
Impressed by your response on this, thanks a bunch! :+1:

**Comment by Craga89** [comment]
No problem @rockerest, it's been need for quite a while! Now to dredge through the other issues I've been putting off... *grumbles*

**Comment by rockerest** [comment]
If it helps you at all, it means a LOT that you - an open source maintainer - are actually maintaining your product. It speaks volumes about you as a dev. Let me know if you want any help with anything (I know almost nothing about the qTip2 internals :anguished:)

**Comment by tibineagu** [comment]
@Craga89 I'm very late to the party but I've recently tried to use qTip2 installed via `npm` and jQuery with `webpack` and I'm not getting anywhere.

Can you please provide a few guidelines for this build system.

Basically i've tried things like [this](https://stackoverflow.com/a/45143334/1541025) (i.e. `require('qtip2')` once `jQuery` was available in the global scope to no success.

I've also tried [this approach](https://laracasts.com/discuss/channels/elixir/how-to-use-jquery-plugins-wwebpack/replies/189331) which seems to be a common way of installing a jQuery plugin via webpack (`require('qtip2')($)`) and still no success.

It would be perfect to be able to install and use your library with our current build system.

**Comment by tibineagu** [comment]
@Craga89 I opened PR #849 adding CommonJS support.

With this in place, `qTip2` may be used with `webpack` as follows.

```js
// webpack.config.js
module.exports = {
    resolve: {
        alias: {
            'jquery': 'jquery/src/jquery',
        },
    },
    module: {
        rules: [
            {
                test: require.resolve('qtip2'),
                loader: 'imports-loader?define=>false',
            },
        ],
    },
}
```
and in your entry file:
```js
import $ from 'jquery'
window.$ = window.jQuery = $;

const qtip = require('qtip2');
```

Until the PR is merged, I will be using my forked library [available here](https://github.com/tibineagu/qTip2/tree/commonjs-support)

**Comment by bluepeter** [comment]
Thanks for this @tibineagu

**Comment by tibineagu** [comment]
@Craga89 gentle nudge regarding this and my PR #849 - if there's anything you want me to change in the PR please let me know.
