### ISSUE TITLE
Minified version fail at creating tip

### ISSUE THREAD

**Issue by joan** [qTip2/qTip2#758]
Hi!
Long time to finally figure out that it come from the "official" minified version…
Your basic demo : http://jsfiddle.net/craga89/fdavn/
With the minified sources : http://jsfiddle.net/488sfcLd/1/
Thanks!

**Comment by Craga89** [comment]
You're using the `basic` alternative build on the second link, which doesn't include any of the plugins, including the `tip` plugin that draws it.
