### ISSUE TITLE
how do you call qtip without hover

### ISSUE THREAD

**Issue by craigcosmo** [qTip2/qTip2#760]
I have a field like this

```
<input name="name" type=""text" id="name>
```
I want to call the tip inside a function like this:

```
function exe(){
1. show tip next to the right of input 
2. add custom content "hello world" to that tip
3. this tip will only disappear on demand, not blur or hover out.
}
```
How would you config that?

**Comment by rajlaksh** [comment]
@craigcosmo your image or code does not show please recheck.

**Comment by craigcosmo** [comment]
thanks, I made change to the comment. I think you can see the issue now

**Comment by rajlaksh** [comment]
$('.qtip qtip-default ').show(); like something

**Comment by craigcosmo** [comment]
Hi raj, thanks. Does it open on demand? like I call a function and it show. then I call close() it close.

**Comment by craigcosmo** [comment]
I figure out. Just add a custom event to the tip. Then trigger the host element with trigger('my_custom_e')

```
$('#space').qtip({
					// prerender: true,
					content: {
						text: i.space
				    },
				    position: {
				        my: 'left center',  
				        at: 'right center'
				    },
				    style: {
				        classes: 'qtip-busy qtip-shadow'
				    },
				    show: 'my_custome_e',
				    hide: 'my_other_e'
				});
```

**Comment by rajlaksh** [comment]
it opens on click on input #name and #pass so outside click it will hide qtip :smile:
