### ISSUE TITLE
Possible js error prevention

### ISSUE THREAD

**Issue by s1c-design** [qTip2/qTip2#761]
Hello,

I download yesterday the full version of qtip 2.2.1
and used it on our project. In all pages the qtip was functioning as expected except for 1 page
where it did not work due to a js error that occured in line 1858
stating that api.options was undefined or null or something like that.
So i had to do this
if(attr === title && api && 'object' === typeof api && api.options && api.options.suppress)

So, obviously in my case for this page the code is not entering this if statement and this might have been caused by faulty code of our project but I am just putting this here in case it helps someone else as well.

**Comment by Craga89** [comment]
Fixed as of 32963b82bb1733563f205b3e9c55b064b1856169
