### ISSUE TITLE
qtip slows down page even when prerender is false

### ISSUE THREAD

**Issue by pieterlukasse** [qTip2/qTip2#771]
I have a page where I want to show a qtip on ~800 items. This is slow if I add the qtip directly via qtip() function. An alternative implementation where the qtips are added and shown on mouseover is much faster, as the qtip() function is only called for the hovered item. I thought the prerender=false setting was supposed to solve this...did I miss something or is it indeed a bug in the version I'm using? I'm using /* qTip2 v2.2.1 | Plugins: tips modal viewport svg imagemap ie6 | Styles: core basic css3 | qtip2.com | Licensed MIT | Sat Sep 06 2014 23:12:07 */

**Comment by Craga89** [comment]
With that amount of items it's still doing a lot of processing, including attaching the event bindings which is the main perf. restriction.

Try taking a look at the Delegation example: http://qtip2.com/guides#events.delegation

**Comment by pieterlukasse** [comment]
yeah, the Delegation example is similar to the solution I am proposing (adding qtips onmouseover). Here is my solution: 

$(e).one('mouseenter', function(event) {
    		  $(this).qtip({
   			     content:  .....

**Comment by Craga89** [comment]
Using `.one` will bind that hander to _each_ element, so it's not much better than qTip with `prerender` set to false. Use `.on` instead and implement the `once`ness yourself

**Comment by pieterlukasse** [comment]
Interesting...funny thing is that in practice it turns out to be much
faster...that's why I logged this issue.
