### ISSUE TITLE
Remove all animations

### ISSUE THREAD

**Issue by mato75** [qTip2/qTip2#773]
Can we remove all animations, positioning, showing, ....?

**Comment by Craga89** [comment]
At that pint wouldn't you jsut use a `<div/>`? ;)

**Comment by mato75** [comment]
Can you give me an example, because I do not understand what styled div has to do with animations on show, reposition,...?

**Comment by Craga89** [comment]
Take a look at the [`show.effect`](http://qtip2.com/options#show.effect), [`hide.effect`](http://qtip2.com/options#hide.effect) and [`position.effect`](http://qtip2.com/options#position.effect)
