### ISSUE TITLE
qTip2 v2.2.1. bower dist doesn't contain full css and js version

### ISSUE THREAD

**Issue by KutuzovGregory** [qTip2/qTip2#777]
github.com/qTip2/bower.git

This repo contains only basic version of qTip2. 

Could you please update it?

**Comment by Craga89** [comment]
It also contains the full build, in the main `jquery.qtip.js` and similar files. Closing

**Comment by mhoffmeyerDC** [comment]
The bower repo still only contains the 2.2.1 version and the bower main is missing the CSS.
