### ISSUE TITLE
Title attribute broken

### ISSUE THREAD

**Issue by AnilRedshift** [qTip2/qTip2#784]
This is a regression from https://github.com/qTip2/qTip2/commit/e4d59b0b5d32d73e9231ebf910fbead056ed42e8
The problem is that the parenthesis for `invalidContent` were improperly removed, causing `string` types to start returning true.

**Comment by AnilRedshift** [comment]
Minimal repro is to make a qtip with `{content: {text: 'some text', title: 'some title'}}`

**Comment by Craga89** [comment]
Fixed as of https://github.com/qTip2/qTip2/commit/727174cf1592beed782f9ed41fc3a5a3bee69a74
