### ISSUE TITLE
typo on page for nightly button

### ISSUE THREAD

**Issue by thezoggy** [qTip2/qTip2#788]
`"Remoe git imagesLoaded submodule in favour of depe..."`- should be Remove

**Comment by Craga89** [comment]
Can you clarify where this is?

**Comment by thezoggy** [comment]
was on the nightly button that looks like has been removed from the Download page

**Comment by Craga89** [comment]
Ahh yes, explains why I couldn't see it! Thanks. Nightly is gone now as I'm striving to make any releases (as few and far between as they've been) as quick as possible when fixes come  in
